Import wiredtiger-wiredtiger-2.8.0-410-g636a7b2.tar.gz from wiredtiger branch mongodb-3.4
ref: 4fb0fd1..7d2e976

WT-2103       add incremental backup testing to format
WT-2223       Add stress testing for in-memory
WT-2343       Assert we don't remove or rename when backup cursor is open
WT-2349       Add ability to open databases read-only
WT-2359       WiredTiger with Python will hang if a calloc failure occurs during __wt_connection_close
WT-2360       Allow disjunctions and combinations of operations in join cursors
WT-2446       Estimate WT cache hit ratio
WT-2450       salvage releases pages, then explicitly evicts them.
WT-2453       Throughput drop in wtperf evict Jenkins tests
WT-2479       dump utility discards table config (JSON)
WT-2504       Should READONLY always read basecfg file?
WT-2505       Review clang analyzer warnings
WT-2508       test programs should remove test directories on the "clean" target
WT-2518       LSM checkpoint handle acquisition optimization
WT-2520       WT_SESSION::verify should not alter tables
WT-2526       mixing and matching readonly and read/write handles
WT-2535       Extend test/format to test for transactions reading their writes
WT-2537       cannot open DB written by WT2.6.1 with WT2.8.0 due to WT_NOTFOUND on recovery
WT-2539       Implement file streaming above pluggable filesystems
WT-2540       Separate stream and file handle methods
WT-2542       fixed-length column store reconciliation overwrites original values
WT-2544       Investigate any thread populating eviction queue
WT-2546       Eviction server not help evict pages sometimes
WT-2547       Add 1-eviction-worker jobs to Jenkins
WT-2548       Cap the amount of data handed to raw compression.
WT-2549       joins using recno keys return no values
WT-2550       java ex_schema example fails
WT-2552       Public API for pluggable filesystems
WT-2553       Document in-memory configuration and WT_CACHE_FULL error return
WT-2556       typo in the Java example code
WT-2557       format test program should discard log files after incremental backup
WT-2558       WT_PAGE structure reorganization
WT-2559       Jenkins Windows segfault in logging code
WT-2560       test/format workload stuck trying to update oldest transaction ID
WT-2562       reconfig02 test failing sometimes on PPC
WT-2565       item 3573 on page at [write-check] is a corrupted cell
WT-2566       All lock operations should be barriers
WT-2567       segfault in test/format log truncate
WT-2568       Java PackTest.java compilation error
WT-2569       win_handle_read should always call GetLastError on error
WT-2570       Minor lint cleanups.
WT-2571       join code cleanup
WT-2572       don't select an in-memory format run if incompatible options configured
WT-2573       free of stack-allocated WT_REF
WT-2574       format doesn't free all allocated configure memory
WT-2576       variable-length column-store out-of-order return
WT-2577       core dump discarding non-existent addresses
WT-2579       in-memory configurations break debugging support
WT-2580       potential SWIG naming conflict in Java
WT-2581       assert multi->disk_image == NULL
WT-2582       cache eviction server error: WT_RESTART
WT-2583       incremental backup can prevent future recovery
WT-2584       don't use periods in error messages
WT-2586       Remove ex_config.c until config cursors are supported
WT-2592       Joins using non-recno key types not working
WT-2593       disk full with pre-allocated log files
WT-2595       Fix compiler warning in packing tests
WT-2598       in-memory FS needs fast lookup on file names
WT-2599       split out the checksum code from the support directory
WT-2600       clean up test program #includes
WT-2602       LSM stress hangs with very large uncompressed pages
WT-2609       Incorrect "skips API_END call" error.
WT-2612       The dist/s_prototypes script is creating a debugging file xxx.
WT-2613       WT Compile windows Alt is returning a C4100 error
WT-2615       Enabling checkpoints in test/format leads to reduced concurrency
WT-2616       In-memory deadlock getting size
WT-2621       WiredTiger fails to compile on MSVC 2013
SERVER-23661  $sample takes disproportionately long time on newly created collection
SERVER-23904  WiredTiger changes for MongoDB 3.3.6